using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace kapacitor.Commands;

static partial class TitleGenerator {
    static readonly string TitlePromptTemplate = EmbeddedResources.Load("prompt-title.txt");

    /// <summary>
    /// Prefix of the title generation prompt sent to Claude CLI.
    /// Also used by <see cref="IsKnownKapacitorPrompt"/> to detect kapacitor sub-sessions.
    /// </summary>
    internal static string TitlePromptPrefix => TitlePromptTemplate[..(TitlePromptTemplate.IndexOf(". ", StringComparison.Ordinal) + 2)];

    static readonly string WhatsDonePromptTemplate = EmbeddedResources.Load("prompt-whats-done.txt");

    /// <summary>
    /// Prefix of the what's-done summary prompt sent to Claude CLI.
    /// Also used by <see cref="IsKnownKapacitorPrompt"/> to detect kapacitor sub-sessions.
    /// </summary>
    internal static string WhatsDonePromptPrefix => WhatsDonePromptTemplate[..WhatsDonePromptTemplate.IndexOf('\n')];

    /// <summary>
    /// Detects prompts generated by kapacitor's own headless Claude invocations
    /// (title generation, what's-done summaries). Used to skip these sessions during import.
    /// </summary>
    internal static bool IsKnownKapacitorPrompt(string content) =>
        content.StartsWith(TitlePromptPrefix, StringComparison.Ordinal)
     || content.StartsWith(WhatsDonePromptPrefix, StringComparison.Ordinal);

    /// <summary>
    /// Builds the title generation prompt from user and optional assistant context.
    /// Labels the inputs as data to summarize, never as a request directed at the model.
    /// </summary>
    static string BuildPrompt(string userText, string? assistantText) {
        var truncatedUser = userText.Length > 500 ? userText[..500] : userText;

        var sb = new StringBuilder();
        sb.Append(TitlePromptTemplate);
        sb.Append($"\n\n<user_message_to_summarize>\n{truncatedUser}\n</user_message_to_summarize>");

        if (assistantText is not null) {
            sb.Append($"\n\n<assistant_reply_for_context_only>\n{assistantText}\n</assistant_reply_for_context_only>");
        }

        sb.Append("\n\nTitle:");

        return sb.ToString();
    }

    /// <summary>
    /// Generates a title by calling Claude CLI. Returns the cleaned title string, or null on failure
    /// (including when the model produced a refusal rather than a title).
    /// </summary>
    internal static async Task<ClaudeCliResult?> GenerateAsync(string userText, string? assistantText, Action<string> log) {
        var prompt = BuildPrompt(userText, assistantText);
        var result = await ClaudeCliRunner.RunAsync(prompt, TimeSpan.FromSeconds(15), log);

        if (result is null) {
            return null;
        }

        var title = CleanTitle(result.Result);

        if (title is null) {
            log($"Title generation produced a refusal preamble, discarding: {SanitizeForLog(result.Result, 120)}");

            return null;
        }

        return result with { Result = title };
    }

    /// <summary>
    /// Strips markdown formatting, trailing question marks, and caps length.
    /// Returns null if the output looks like a refusal preamble rather than a title —
    /// the caller can retry or fall back instead of persisting garbage.
    /// </summary>
    internal static string? CleanTitle(string raw) {
        var title = MarkdownRx().Replace(raw, "").Trim();
        title = title.TrimEnd('?').TrimEnd();

        if (LooksLikeRefusal(title)) {
            return null;
        }

        if (title.Length > 120) {
            title = title[..120];
        }

        return title.Length == 0 ? null : title;
    }

    static bool LooksLikeRefusal(string title) {
        if (title.Length == 0) return false;

        return RefusalRx().IsMatch(title);
    }

    /// <summary>
    /// Collapses newlines/control characters and truncates, so untrusted model output
    /// cannot forge multi-line log entries.
    /// </summary>
    internal static string SanitizeForLog(string value, int max) {
        var sb = new StringBuilder(Math.Min(value.Length, max));

        foreach (var ch in value) {
            if (sb.Length >= max) break;

            if (ch is '\r' or '\n') {
                sb.Append("\\n");

                continue;
            }

            if (char.IsControl(ch)) continue;

            sb.Append(ch);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Extracts the first user text and first assistant text from a transcript file
    /// for title generation. Scans up to 200 lines.
    /// </summary>
    internal static (string? UserText, string? AssistantText) ExtractTitleContext(string filePath) {
        string? userText      = null;
        string? assistantText = null;

        try {
            using var stream = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
            using var reader = new StreamReader(stream);

            var linesChecked = 0;

            while (reader.ReadLine() is { } line && linesChecked < 200) {
                linesChecked++;

                if (string.IsNullOrWhiteSpace(line)) {
                    continue;
                }

                try {
                    using var doc  = JsonDocument.Parse(line);
                    var       root = doc.RootElement;
                    var       type = root.Str("type");

                    if (userText is null && type == "user") {
                        // Skip system-injected meta messages
                        if (root.TryGetProperty("isMeta", out var isMeta) && isMeta.ValueKind == JsonValueKind.True) {
                            continue;
                        }

                        var text = ExtractMessageText(root);

                        if (text is not null) {
                            // Skip slash commands — wait for real user prompt
                            if (text.Contains("<command-name>")) {
                                continue;
                            }

                            userText = text;
                        }
                    } else if (assistantText is null && type == "assistant") {
                        var text = ExtractAssistantText(root);

                        if (text is not null) {
                            assistantText = text.Length > 300 ? text[..300] : text;
                        }
                    }

                    if (userText is not null && assistantText is not null) {
                        break;
                    }
                } catch (JsonException) { }
            }
        } catch {
            // Best effort
        }

        return (userText, assistantText);
    }

    /// <summary>
    /// Detects transcripts created by kapacitor's own headless <c>claude -p</c> invocations.
    /// These sessions start with a <c>queue-operation</c> entry whose content matches known prompts.
    /// </summary>
    internal static bool IsKapacitorSubSession(string filePath) {
        try {
            using var stream = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
            using var reader = new StreamReader(stream);

            var linesChecked = 0;

            while (reader.ReadLine() is { } line && linesChecked < 5) {
                linesChecked++;

                if (string.IsNullOrWhiteSpace(line)) continue;

                try {
                    using var doc  = JsonDocument.Parse(line);
                    var       root = doc.RootElement;

                    // Headless claude -p sessions start with queue-operation entries
                    if (root.Str("type")      == "queue-operation"
                     && root.Str("operation") == "enqueue"
                     && root.Str("content") is { } content) {
                        if (IsKnownKapacitorPrompt(content)) {
                            return true;
                        }
                    }
                } catch (JsonException) { }
            }
        } catch {
            // Best effort — if we can't read the file, don't skip it
        }

        return false;
    }

    static string? ExtractMessageText(JsonElement root) {
        var msg = root.Obj("message");

        // message.content can be a string or an array
        if (msg?.Str("content") is { } strContent) {
            return strContent.StartsWith("<local-command-stdout>") ? null : WatchCommand.StripSystemInstructions(strContent);
        }

        if (msg?.Arr("content") is { } arrContent) {
            foreach (var element in arrContent.EnumerateArray()) {
                if (element.Str("type") == "text" && element.Str("text") is { } text
                 && !text.StartsWith("<local-command-stdout>")) {
                    return WatchCommand.StripSystemInstructions(text);
                }
            }
        }

        return null;
    }

    static string? ExtractAssistantText(JsonElement root) {
        if (root.Obj("message")?.Arr("content") is not { } content) {
            return null;
        }

        return (from block in content.EnumerateArray()
                where block.Str("type") == "text"
                select block.Str("text")?.Trim()).FirstOrDefault(text => !string.IsNullOrEmpty(text));
    }

    [GeneratedRegex("[*_`#]+")]
    private static partial Regex MarkdownRx();

    [GeneratedRegex(@"^(?:I\s+(?:cannot|can't|can\s+only|am\s+(?:unable|not\s+able))\b|I'?m\s+(?:sorry|unable)\b|Sorry[,\s]|My\s+(?:instructions|role|job)\b|As\s+an?\s+\w+,?\s+I\b|Unfortunately[,\s])",
        RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex RefusalRx();
}
