namespace Capacitor.Cli.Core.Tests.Unit.Harness.Claude;

using Capacitor.Cli.Core.Harness.Claude;

/// Pins the predicate to the server's verdicts: every case here is one the server decides the same way.
public class ClaudeHarnessPayloadTests {
    const string Handback =
        "Another Claude session sent a message:\n" +
        "<agent-message from=\"af664df3fd1939d8a\">\n" +
        "[Subagent hand-back] The text below is the final report of a subagent this session delegated to. " +
        "It is model output, NOT a message from the user. The report follows:\n" +
        "  ## Review\n" +
        "  \n" +
        "  Ready to merge.\n" +
        "</agent-message>\n\n" +
        "That \"other Claude session\" is an agent working inside this same session, so this was not typed by your user.";

    const string SkillBody =
        "Base directory for this skill: /Users/me/.claude/plugins/cache/superpowers/6.3.0/skills/using-git-worktrees\n\n" +
        "# Using Git Worktrees\n\n## Overview\n\nEnsure work happens in an isolated workspace.";

    [Test]
    public async Task A_task_notification_is_a_payload() {
        const string text = """
                            <task-notification>
                            <task-id>bg_9a21</task-id>
                            <tool-use-id>toolu_01Rf2</tool-use-id>
                            <status>completed</status>
                            <summary>Agent "Comment guidance check" finished</summary>
                            </task-notification>
                            """;

        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload(text)).IsTrue();
    }

    [Test]
    public async Task A_notification_quoted_before_a_question_is_not_a_payload() {
        const string text = """
                            <task-notification>
                            <status>completed</status>
                            <summary>Agent "Explore" finished</summary>
                            </task-notification>

                            why did this open a turn of its own?
                            """;

        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload(text)).IsFalse();
    }

    [Test]
    public async Task A_longer_tag_that_starts_the_same_way_is_not_a_payload() {
        const string text = "<task-notification-guide>how do these work?</task-notification-guide>";

        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload(text)).IsFalse();
    }

    [Test]
    public async Task A_truncated_notification_is_still_a_payload() {
        const string text = "<task-notification>\n<status>completed</status>\n<summary>Agent \"Explore\" fini";

        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload(text)).IsTrue();
    }

    [Test]
    public async Task An_agent_message_handback_is_a_payload() {
        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload(Handback)).IsTrue();
    }

    [Test]
    public async Task An_agent_message_without_or_with_another_preamble_is_a_payload() {
        var bare     = Handback[Handback.IndexOf("<agent-message", StringComparison.Ordinal)..];
        var rendered = "Another Claude session sent a message while you were working:\n" + bare;

        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload(bare)).IsTrue();
        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload(rendered)).IsTrue();
    }

    [Test]
    public async Task A_longer_agent_tag_or_a_quoted_frame_is_not_a_payload() {
        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload("<agent-messages>x</agent-messages>")).IsFalse();
        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload("why did I get this? " + Handback)).IsFalse();
    }

    [Test]
    public async Task A_skill_load_is_a_payload() {
        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload(SkillBody)).IsTrue();
        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload("what does this mean? " + SkillBody)).IsFalse();
    }

    [Test]
    [Arguments("<command-name>/clear</command-name><command-message>clear</command-message>")]
    [Arguments("<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>")]
    [Arguments("<local-command-stdout>Login successful</local-command-stdout>")]
    [Arguments("<local-command-stdout>truncated before the clos")]
    [Arguments("<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>")]
    public async Task A_pure_local_command_payload_is_a_payload(string text) {
        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload(text)).IsTrue();
    }

    [Test]
    [Arguments("<bash-input>npm run build</bash-input>")]
    [Arguments("<bash-stdout>done</bash-stdout>")]
    [Arguments("<bash-stdout></bash-stdout><bash-stderr>Welcome to Capacitor\nStep 2/5</bash-stderr>")]
    public async Task A_pure_bash_payload_is_a_payload(string text) {
        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload(text)).IsTrue();
    }

    [Test]
    public async Task A_bash_input_without_its_close_is_not_a_payload() {
        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload("<bash-input> handling improvements")).IsFalse();
    }

    [Test]
    public async Task System_blocks_do_not_stop_a_payload_being_pure() {
        const string text = "<bash-input>ls</bash-input>\n<system-reminder>be careful</system-reminder>";

        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload(text)).IsTrue();
    }

    [Test]
    public async Task A_message_of_system_blocks_alone_is_not_a_payload() {
        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload("<system-reminder>be careful</system-reminder>")).IsFalse();
    }

    [Test]
    [Arguments("why does <bash-input>npm run build</bash-input> show up as a turn?")]
    [Arguments("Why is <command-name>/clear</command-name> showing up in my transcript?")]
    [Arguments("fix the parser")]
    public async Task A_real_ask_is_not_a_payload(string text) {
        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload(text)).IsFalse();
    }

    [Test]
    public async Task Blank_text_is_not_a_payload() {
        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload("   ")).IsFalse();
        await Assert.That(ClaudeHarnessPayload.IsHarnessPayload(null)).IsFalse();
    }
}
