using System.Text.Json;
using Capacitor.Cli.Core;

namespace Capacitor.Cli.Commands;

/// Transcript-side helpers for title generation: extracting the first user/assistant text a
/// title is generated from, and recognising kcap's own headless sub-sessions. The generation
/// itself lives in Core's <see cref="TitleGeneration"/>, shared with the daemon.
static class TitleGenerator {
    static readonly string WhatsDonePromptTemplate = EmbeddedResources.Load("prompt-whats-done.txt");

    /// <summary>
    /// Prefix of the what's-done summary prompt sent to Claude CLI.
    /// Also used by <see cref="IsKnownCapacitorPrompt"/> to detect kcap sub-sessions.
    /// </summary>
    internal static string WhatsDonePromptPrefix => WhatsDonePromptTemplate[..WhatsDonePromptTemplate.IndexOf('\n')];

    /// <summary>
    /// Detects prompts generated by kcap's own headless Claude invocations
    /// (title generation, what's-done summaries). Used to skip these sessions during import.
    /// </summary>
    internal static bool IsKnownCapacitorPrompt(string content) =>
        content.StartsWith(TitleGeneration.TitlePromptPrefix, StringComparison.Ordinal)
     || content.StartsWith(WhatsDonePromptPrefix, StringComparison.Ordinal);

    /// <summary>
    /// Extracts the first user text and first assistant text from a transcript file
    /// for title generation. Scans up to 200 lines.
    /// </summary>
    internal static (string? UserText, string? AssistantText) ExtractTitleContext(string filePath) {
        string? userText      = null;
        string? assistantText = null;

        try {
            using var stream = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
            using var reader = new StreamReader(stream);

            var linesChecked = 0;

            while (reader.ReadLine() is { } line && linesChecked < 200) {
                linesChecked++;

                if (string.IsNullOrWhiteSpace(line)) {
                    continue;
                }

                try {
                    using var doc  = JsonDocument.Parse(line);
                    var       root = doc.RootElement;
                    var       type = root.Str("type");

                    if (userText is null && type == "user") {
                        // Skip system-injected meta messages
                        if (root.TryGetProperty("isMeta", out var isMeta) && isMeta.ValueKind == JsonValueKind.True) {
                            continue;
                        }

                        var text = ExtractMessageText(root);

                        if (text is not null) {
                            // Skip slash commands — wait for real user prompt
                            if (text.Contains("<command-name>")) {
                                continue;
                            }

                            userText = text;
                        }
                    } else if (assistantText is null && type == "assistant") {
                        var text = ExtractAssistantText(root);

                        if (text is not null) {
                            assistantText = text.Length > 300 ? text[..300] : text;
                        }
                    }

                    if (userText is not null && assistantText is not null) {
                        break;
                    }
                } catch (JsonException) { }
            }
        } catch {
            // Best effort
        }

        return (userText, assistantText);
    }

    /// <summary>
    /// Codex-shape variant of <see cref="ExtractTitleContext"/>. Reads the rollout looking for
    /// the first user-authored <c>response_item</c> (skipping the synthetic
    /// <c>&lt;environment_context&gt;</c> block) and the first assistant <c>response_item</c>
    /// with an <c>output_text</c> block.
    /// </summary>
    internal static (string? UserText, string? AssistantText) ExtractCodexTitleContext(string filePath) {
        string? userText      = null;
        string? assistantText = null;

        try {
            using var stream = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
            using var reader = new StreamReader(stream);

            var linesChecked = 0;

            while (reader.ReadLine() is { } line && linesChecked < 200) {
                linesChecked++;

                if (string.IsNullOrWhiteSpace(line)) continue;

                try {
                    using var doc  = JsonDocument.Parse(line);
                    var       root = doc.RootElement;

                    // Codex wraps every event under a top-level "type" + "payload" envelope.
                    if (root.Str("type") != "response_item") continue;

                    var payload = root.Obj("payload");

                    if (payload?.Str("type") != "message") continue;

                    var role = payload.Value.Str("role");

                    if (userText is null && role == "user") {
                        var text = ExtractCodexBlockText(payload.Value, "input_text");

                        // Skip codex-injected wrappers that surface as role:"user" messages
                        // before (or interleaved with) real user prompts. Without these
                        // skips, titles get generated from the repo's AGENTS.md content or
                        // an interrupt notice instead of the actual work request.
                        if (text is not null && !IsCodexInjectedUserPrelude(text)) {
                            userText = text;
                        }
                    } else if (assistantText is null && role == "assistant") {
                        var text = ExtractCodexBlockText(payload.Value, "output_text");

                        if (text is not null) {
                            assistantText = text.Length > 300 ? text[..300] : text;
                        }
                    }

                    if (userText is not null && assistantText is not null) break;
                } catch (JsonException) { }
            }
        } catch {
            // Best effort
        }

        return (userText, assistantText);
    }

    /// <summary>
    /// Detects role:"user" payload bodies that codex synthesises around the real
    /// conversation — none of which represent a user prompt and all of which would
    /// otherwise dominate the title context window. Observed on real rollouts:
    /// <list type="bullet">
    ///   <item><c>&lt;environment_context&gt;...</c> — every session gets one.</item>
    ///   <item><c># AGENTS.md instructions for &lt;path&gt;...</c> — repo context auto-injected
    ///   when an AGENTS.md is found anywhere up the cwd tree.</item>
    ///   <item><c>&lt;turn_aborted&gt;...</c> — emitted when the user interrupts a turn,
    ///   which can land before a follow-up prompt in the same session.</item>
    /// </list>
    /// </summary>
    internal static bool IsCodexInjectedUserPrelude(string text) =>
        text.StartsWith("<environment_context>",     StringComparison.Ordinal)
     || text.StartsWith("# AGENTS.md instructions",  StringComparison.Ordinal)
     || text.StartsWith("<turn_aborted>",            StringComparison.Ordinal);

    internal static string? ExtractCodexBlockText(JsonElement payload, string blockType) {
        if (payload.Arr("content") is not { } content) return null;

        foreach (var block in content.EnumerateArray()) {
            if (block.Str("type") == blockType && block.Str("text") is { } text && !string.IsNullOrEmpty(text)) {
                return text;
            }
        }

        return null;
    }

    /// <summary>
    /// Detects transcripts created by kcap's own headless <c>claude -p</c> invocations.
    /// These sessions start with a <c>queue-operation</c> entry whose content matches known prompts.
    /// </summary>
    internal static bool IsCapacitorSubSession(string filePath) {
        try {
            using var stream = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
            using var reader = new StreamReader(stream);

            var linesChecked = 0;

            while (reader.ReadLine() is { } line && linesChecked < 5) {
                linesChecked++;

                if (string.IsNullOrWhiteSpace(line)) continue;

                try {
                    using var doc  = JsonDocument.Parse(line);
                    var       root = doc.RootElement;

                    // Headless claude -p sessions start with queue-operation entries
                    if (root.Str("type")      == "queue-operation"
                     && root.Str("operation") == "enqueue"
                     && root.Str("content") is { } content) {
                        if (IsKnownCapacitorPrompt(content)) {
                            return true;
                        }
                    }
                } catch (JsonException) { }
            }
        } catch {
            // Best effort — if we can't read the file, don't skip it
        }

        return false;
    }

    static string? ExtractMessageText(JsonElement root) {
        var msg = root.Obj("message");

        // message.content can be a string or an array
        if (msg?.Str("content") is { } strContent) {
            return strContent.StartsWith("<local-command-stdout>") ? null : WatchCommand.StripSystemInstructions(strContent);
        }

        if (msg?.Arr("content") is { } arrContent) {
            foreach (var element in arrContent.EnumerateArray()) {
                if (element.Str("type") == "text" && element.Str("text") is { } text
                 && !text.StartsWith("<local-command-stdout>")) {
                    return WatchCommand.StripSystemInstructions(text);
                }
            }
        }

        return null;
    }

    static string? ExtractAssistantText(JsonElement root) {
        if (root.Obj("message")?.Arr("content") is not { } content) {
            return null;
        }

        return (from block in content.EnumerateArray()
                where block.Str("type") == "text"
                select block.Str("text")?.Trim()).FirstOrDefault(text => !string.IsNullOrEmpty(text));
    }
}
