#!/usr/bin/env python3
"""Render capability-matrix.md from matrix.json: one row per entry, the columns #778 and #962 read.

Usage: report.py [--matrix FILE] [--out FILE]
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

KIT = Path(__file__).resolve().parent

VISIBLE = ("visible_first_turn", "visible_after_reload")
COLUMNS = ("Entry", "Version tested", "Modes", "Native root", "Roots consumed", "Startup mechanism proven",
           "Exclusion preserving load", "Vendor-isolated destination", "Reload path", "GUI status", "Minimum version")

# GUI launch modes the kit cannot drive; the findings carry a manual procedure for each.
GUI_STATUS = {
    "cursor": "Cursor desktop: untested (manual procedure in findings.md)",
    "agy": "Antigravity IDE: untested (manual procedure in findings.md)",
    "agy-dirlayout": "Antigravity IDE: untested (manual procedure in findings.md)",
    "agy-clidir": "Antigravity IDE: untested (manual procedure in findings.md)",
    "kiro": "Kiro IDE: untested (manual procedure in findings.md)",
}


def load_rows(path: Path) -> list[dict]:
    return json.loads(path.read_text())


def summarise(rows: list[dict]) -> list[dict]:
    by_entry: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_entry[r["entry"]].append(r)
    consumed_by: dict[str, set[str]] = defaultdict(set)
    for r in rows:
        if r["scenario"] == "S4" and r["verdict"] in VISIBLE and r["root"]:
            consumed_by[r["root"]].add(r["entry"])
    out = []
    for entry in sorted(by_entry):
        rs = by_entry[entry]
        versions = sorted({r["version"] for r in rs})
        modes = sorted({r["mode"] for r in rs})
        native = next((r["root"] for r in rs if r["scenario"] == "S1" and r["root"]), "")
        roots = sorted({r["root"] for r in rs if r["scenario"] == "S4" and r["verdict"] in VISIBLE and r["root"]})
        leaked = sorted({r["root"] for r in rs if r["scenario"] == "S4" and r["verdict"] == "leaked"})
        mechanisms = sorted({f"{r['mechanism']} ({r['mode']})" for r in rs
                             if r["scenario"] == "S2" and r["verdict"] in VISIBLE and r["mechanism"]})
        exclusions = sorted({r["exclusion"] for r in rs if r["scenario"] == "S3" and r["verdict"] in VISIBLE})
        reload = sorted({r["mechanism"] for r in rs if r["verdict"] == "visible_after_reload" and r["mechanism"]})
        untested = sorted({r["notes"][:80] for r in rs if r["verdict"] == "untested" and r["scenario"] == "S1"})
        isolated = [root for root in roots if consumed_by[root] == {entry}]
        s1 = {r["verdict"] for r in rs if r["scenario"] == "S1"}
        status = "measured" if s1 & set(VISIBLE) else ("untested: " + "; ".join(untested) if untested else "no S1 row")
        out.append({
            "Entry": entry,
            "Version tested": ", ".join(versions),
            "Modes": ", ".join(modes),
            "Native root": native,
            "Roots consumed": ", ".join(roots) + (f" (undocumented: {', '.join(leaked)})" if leaked else ""),
            "Startup mechanism proven": "; ".join(mechanisms) if mechanisms else ("none" if status == "measured" else "—"),
            "Exclusion preserving load": ", ".join(exclusions) if exclusions else ("none" if status == "measured" else "—"),
            "Vendor-isolated destination": ", ".join(isolated) if isolated else ("none" if status == "measured" else "—"),
            "Reload path": "; ".join(reload) if reload else ("none" if status == "measured" else "—"),
            "GUI status": GUI_STATUS.get(entry, "n/a"),
            "Minimum version": ", ".join(versions) if status == "measured" else "—",
            "_status": status,
        })
    return out


def render(summary: list[dict]) -> str:
    lines = ["# Capability matrix — repo-local skill discovery", "",
             "Generated by `report.py` from `matrix.json`; do not edit by hand. A `—` cell means the entry",
             "could not run (see its status line below and `findings.md`).", "",
             "| " + " | ".join(COLUMNS) + " |", "|" + " -- |" * len(COLUMNS)]
    for row in summary:
        lines.append("| " + " | ".join(str(row[c]).replace("|", "\\|") for c in COLUMNS) + " |")
    lines += ["", "## Status per entry", ""]
    for row in summary:
        lines.append(f"- `{row['Entry']}`: {row['_status']}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--matrix", type=Path, default=KIT / "matrix.json")
    p.add_argument("--out", type=Path, default=KIT / "capability-matrix.md")
    args = p.parse_args(argv)
    args.out.write_text(render(summarise(load_rows(args.matrix))))
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
